sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts, only:[:create, :destroy]
end

sample_app/app/views/layouts/_footer.html.erb
<div class= "container-fluid footer">
    <div class="d-flex flex-row justify-content-around align-items-center">
        <div class="p-2">Sample App footer</div>
        <div class="p-2">Made by Nguyen Phuong Anh - 20165740</div>
    </div>
</div>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
      <div class="row">
      <div class= "col">
        <%= link_to "SAMPLE APP", '/', id: "logo" %>
        </div>
        <div class="col">
        <nav>
          <ul class="nav justify-content-end" id="navbar">
            <li class= "nav-item"><%= link_to "Home", '/', class: "nav-link" %></li>
            <li class= "nav-item"><%= link_to "Help", help_path, class: "nav-link" %></li>
            <li class= "nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class= "nav-item"><%= link_to "Sign up", signup_path, class: "nav-link" %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
            <li class= "nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </nav>
        
        </div>
        </div>
      </div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class= "container-fluid content">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>